### ISSUE TITLE
When will you publish this repo?

### ISSUE THREAD

**Issue by kiitaamuuraa** [xjli/r2r_vln#1]
Thank you for your work. I am a practitioner who VLN recently.
I am interested in using pretrained language model in VLN tasks. I would like to reproduce your work.
Thank you,

**Comment by xjli** [comment]
Sorry for this, I was working on another heavy project, recently just had time to wrap up this codebase, may not be clean enough :).

**Comment by kiitaamuuraa** [comment]
I really appreciated you published your codebase.
Thank you!
