### ISSUE TITLE
No such file or directory: 'tasks/R2R/data/R2R_bi_12700_seed10-60_literal_speaker_data_aug_paths_unk.json'

### ISSUE THREAD

**Issue by HubHop** [xjli/r2r_vln#3]
Hi Xiujun,

Thanks for your work and source code. I came across this error when training, could you please tell me where I can find this file?

Cheers

**Comment by xjli** [comment]
wget https://xiuldlstorage.blob.core.windows.net/r2r/public/emnlp/data/R2R_bi_12700_seed10-60_literal_speaker_data_aug_paths_unk.json

wget https://xiuldlstorage.blob.core.windows.net/r2r/public/emnlp/data/R2R_bi_12700_seed10-60_literal_speaker_data_augmentation_paths.json

I put the two json paths there, you can try to download and put them into the right path. Thanks.

**Comment by HubHop** [comment]
OK, thank you!
